name: main

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo test

  tag:
    runs-on: ubuntu-latest
    needs: dummy
    steps:
      - uses: actions/checkout@v3

      - id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - uses: ./
        with:
          github-token: ${{ steps.app-token.outputs.token }}
