name: push

on:
  push:
    branches-ignore:
      - main
    tags:
      - "*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          dry-run: true
